theme: jekyll-theme-minimal
title: 小黎的博客主页
description: 一个关注rust世界的站点!

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
